language: php
php:
  - 5.5
  - 5.4

install:
  - git clone http://github.com/zenovich/runkit.git runkit
  - cd runkit
  - phpize
  - ./configure
  - make
  - sudo make install
  - echo "extension=runkit.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - cd ..
  - composer self-update
  - composer install

before_script: composer require task/cli ~0.1

script: vendor/bin/task test

after_script: vendor/bin/coveralls -v
